name: tests

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install numpy scipy scikit-image tifffile trimesh pandas pyyaml pytest
          pip install -e .

      - name: Run tests
        run: pytest -q

